# 모든 서버가 기본으로 가져야할 공통 설정

# 패키지 업데이트
- name: Update dnf
  become: yes
  dnf:
    update_cache: yes

# 공통 패키지 설치
- name: Install common packages
  become: yes
  dnf:
    name:
      - curl
      - git
      - vim
      - unzip
      - tar
      - net-tools
      - jq                         # JSON 처리 도구 (AWS CLI 출력 파싱용)
    state: present

# 타임존 설정
- name: Set Timezone
  become: yes
  timezone:
    name: Asia/Seoul